### PR TITLE
Modernize

### PR DESCRIPTION
**Pull request by fosskers**
### TODO
- [x] Module name: `Deque` -> `Data.Deque`
- [x] Added more typeclass instances
- [x] **Swapped behaviour of `shiftLeft` and `shiftRight` to match bit-shifting**
- [x] Improved `uncons` and `unsnoc`
- [x] Added safe `head` and `last`
- [x] Added docstrings
- [x] Dropped `base-prelude` usage

### Motivation
I'd like to use a Dequeue for a project of mine, and yours is the most featureful. This PR updates the library to be usable with `stack`, improved documentation, and tweaks code where appropriate.

### CODE REVIEW

**Comment by fosskers** [comment]
Hmm, I could also improve your travis config. What lower bound of GHC do you want to support?

**Comment by fosskers** [comment]
Current bounds support `ghc-8.0` and `ghc-7.10`.

**Comment by nikita-volkov** [comment]
Thanks for your contribution, however

* Most of this is style changes. There are reasons, why I apply the style that the project uses. Whether you like it or not, it is only a matter of a personal opinion. So, when in Rome...

* The package was already usable with Stack. No need to change anything about it for that.

So, I guess I can only merge the new typeclass instances, `head` and `tail` and docs, if you update your PR accordingly.

**Comment by fosskers** [comment]
Hey Nikita, thanks for checking it out. I'll admit that changing the layout of the `.cabal` was purely aesthetic (minus removing all the unnecessary language extensions), but the rest of the changes were thought out:

- `Deque` -> `Data.Deque` is appropriate because `Deque` is a new data structure
- The changed semantics of `shiftLeft` and `shiftRight` is to reduce confusion, I claim the current (0.1) behaviour is a mistake
- case-ladder style (in `uncons`, etc) isn't idiomatic
- Other changes were spurred by recommendations from `hlint`

And I realize that you wrote `base-prelude` and thus are probably keen to use it, but I saw dropping it as a simplification of the project. There are many alternate preludes, but this library is small enough not to need one.

**Comment by nikita-volkov** [comment]
>  I'll admit that changing the layout of the `.cabal` was purely aesthetic (minus removing all the unnecessary language extensions), but the rest of the changes were thought out:

I can go for dropping the unnecessary extensions. As for the rest of Cabal: I follow a convention of declaring the used extensions in Cabal instead of the file header, I'm strongly against the suggested formatting of Cabal file for multiple reasons, and I am against specifying the warning flags in Cabal.

> - `Deque` -> `Data.Deque` is appropriate because `Deque` is a new data structure

There's been endless discussions about it. See https://www.reddit.com/r/haskell/comments/1qrilm/packages_and_namespaces_naming_convention/ for instance. I follow that convention as much as many other modern authors and I am strongly opinionated about that.

> - The changed semantics of `shiftLeft` and `shiftRight` is to reduce confusion, I claim the current (0.1) behaviour is a mistake

I agree. I actually intended the opposite behaviour. Thanks for discovering that.

> - case-ladder style (in `uncons`, etc) isn't idiomatic

This is highly debatable. I have multiple reasons to prefer this over the multiple definitions of the same function. Let's just skip that without arguing.

> - Other changes were spurred by recommendations from `hlint`

Which?

> And I realize that you wrote `base-prelude` and thus are probably keen to use it, but I saw dropping it as a simplification of the project. There are many alternate preludes, but this library is small enough not to need one.

I'm not highly opinionated about that. Using "base-prelude" by default makes the development more efficient for me and is guaranteed to bring only one extra-dependency on top of "base". But again I won't act opinionated about dropping that dependency.

**Comment by fosskers** [comment]
Ah, it looks like you were the original poster in that Reddit thread. I remember seeing that ages ago when it was originally posted. Cool, I'll switch `Data.Deque` back to `Deque`. I'll also revert the changes to the `.cabal`, except the language extentions that weren't needed. I personally like to keep warning flags in my `.cabal` so that [intero](http://commercialhaskell.github.io/intero/) picks them up, but I'll remove them if that's your preference.

Here is the output of `hlint` on your `master`:

```console
Found:
  fromList list = Deque [] list
Why not:
  fromList = Deque []

library/Deque.hs:20:3: Warning: Use maybe
Found:
  fromMaybe deque $ fmap (\ (a, b) -> snoc a b) $ uncons deque
Why not:
  maybe deque (\ (a, b) -> snoc a b) (uncons deque)

library/Deque.hs:21:3: Suggestion: Use <$>
Found:
  fmap (\ (a, b) -> snoc a b) $ uncons deque
Why not:
  ((\ (a, b) -> snoc a b) Control.Applicative.<$> uncons deque)

library/Deque.hs:21:9: Suggestion: Use uncurry
Found:
  \ (a, b) -> snoc a b
Why not:
  uncurry snoc
Note: increases laziness

library/Deque.hs:28:3: Warning: Use maybe
Found:
  fromMaybe deque $ fmap (\ (a, b) -> cons a b) $ unsnoc deque
Why not:
  maybe deque (\ (a, b) -> cons a b) (unsnoc deque)

library/Deque.hs:29:3: Suggestion: Use <$>
Found:
  fmap (\ (a, b) -> cons a b) $ unsnoc deque
Why not:
  ((\ (a, b) -> cons a b) Control.Applicative.<$> unsnoc deque)

library/Deque.hs:29:9: Suggestion: Use uncurry
Found:
  \ (a, b) -> cons a b
Why not:
  uncurry cons
Note: increases laziness

library/Deque.hs:36:9: Warning: Redundant bracket
Found:
  (snocList)
Why not:
  snocList

library/Deque.hs:42:24: Warning: Redundant bracket
Found:
  (consList)
Why not:
  consList
```
All of which are corrected in the PR.

**Comment by nikita-volkov** [comment]
Okay. I've merged some parts of it. I've reverted a lot of changes though.

**Comment by fosskers** [comment]
Thanks Nikita.

**Pull request merged**
